//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoExamen {
	using System;
	
	
	/// <summary>
	///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	/// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resource1 {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resource1() {
		}
		
		/// <summary>
		///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrabajoExamen.Resource1", typeof(Resource1).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap cindy {
			get {
				object obj = ResourceManager.GetObject("cindy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap circulo {
			get {
				object obj = ResourceManager.GetObject("circulo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap cuadrado {
			get {
				object obj = ResourceManager.GetObject("cuadrado", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap cubo {
			get {
				object obj = ResourceManager.GetObject("cubo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap esfera {
			get {
				object obj = ResourceManager.GetObject("esfera", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap login {
			get {
				object obj = ResourceManager.GetObject("login", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap pasteleria {
			get {
				object obj = ResourceManager.GetObject("pasteleria", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap piramide {
			get {
				object obj = ResourceManager.GetObject("piramide", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap rectangulo {
			get {
				object obj = ResourceManager.GetObject("rectangulo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap sam {
			get {
				object obj = ResourceManager.GetObject("sam", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap ticket {
			get {
				object obj = ResourceManager.GetObject("ticket", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap trapecio {
			get {
				object obj = ResourceManager.GetObject("trapecio", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap triangulo {
			get {
				object obj = ResourceManager.GetObject("triangulo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap untitled_0__1_ {
			get {
				object obj = ResourceManager.GetObject("untitled-0 (1)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
